"""Seed demo pharmacy catalogue + stock batches.

Run from the backend/ directory:
    python scripts/seed_medicines.py

Idempotent — skips drugs that already exist for the demo clinic.
Creates DrugItems + one or two StockBatches per drug.
"""
import asyncio
import sys
import uuid
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine, async_sessionmaker

from app.core.config import settings
from app.models import *  # noqa: F401,F403
from app.models.inventory import DrugItem, StockBatch

DEMO_TENANT_ID = "00000000-0000-0000-0000-000000000001"
DEMO_CLINIC_ID = "00000000-0000-0000-0000-000000000002"

TODAY = date.today().isoformat()

# ── Drug catalogue ────────────────────────────────────────────────────────────
# Columns:
#   name, generic_name, brand_name, drug_code, form, strength, unit,
#   category, manufacturer, unit_cost, selling_price,
#   requires_prescription, is_controlled, schedule_class,
#   reorder_level, reorder_quantity,
#   batches: list of (batch_no, qty, unit_cost, expiry_days_from_today, supplier)

DRUGS = [
    # ── Antibiotics ──────────────────────────────────────────────────────────
    {
        "name": "Amoxicillin 500mg Capsules",
        "generic_name": "Amoxicillin",
        "brand_name": "Amoxil",
        "drug_code": "0093-3147-01",
        "form": "capsule",
        "strength": "500mg",
        "unit": "capsule",
        "category": "Antibiotics",
        "manufacturer": "GlaxoSmithKline",
        "unit_cost": 0.25,
        "selling_price": 0.75,
        "requires_prescription": True,
        "reorder_level": 50,
        "reorder_quantity": 500,
        "batches": [
            ("AMX-2024-001", 500, 0.25, 365, "MedSupply Co."),
            ("AMX-2024-002", 300, 0.25, 540, "MedSupply Co."),
        ],
    },
    {
        "name": "Azithromycin 250mg Tablets",
        "generic_name": "Azithromycin",
        "brand_name": "Zithromax",
        "drug_code": "0069-3060-30",
        "form": "tablet",
        "strength": "250mg",
        "unit": "tablet",
        "category": "Antibiotics",
        "manufacturer": "Pfizer",
        "unit_cost": 1.20,
        "selling_price": 3.50,
        "requires_prescription": True,
        "reorder_level": 30,
        "reorder_quantity": 200,
        "batches": [
            ("AZI-2024-001", 200, 1.20, 400, "PharmaDist Inc."),
        ],
    },
    {
        "name": "Ciprofloxacin 500mg Tablets",
        "generic_name": "Ciprofloxacin",
        "brand_name": "Cipro",
        "drug_code": "0026-8512-51",
        "form": "tablet",
        "strength": "500mg",
        "unit": "tablet",
        "category": "Antibiotics",
        "manufacturer": "Bayer",
        "unit_cost": 0.80,
        "selling_price": 2.50,
        "requires_prescription": True,
        "reorder_level": 40,
        "reorder_quantity": 300,
        "batches": [
            ("CIP-2024-001", 300, 0.80, 450, "MedSupply Co."),
            ("CIP-2024-002", 200, 0.80, 600, "MedSupply Co."),
        ],
    },
    {
        "name": "Metronidazole 400mg Tablets",
        "generic_name": "Metronidazole",
        "brand_name": "Flagyl",
        "drug_code": "0025-1821-31",
        "form": "tablet",
        "strength": "400mg",
        "unit": "tablet",
        "category": "Antibiotics",
        "manufacturer": "Pfizer",
        "unit_cost": 0.15,
        "selling_price": 0.50,
        "requires_prescription": True,
        "reorder_level": 50,
        "reorder_quantity": 400,
        "batches": [
            ("MET-2024-001", 400, 0.15, 500, "PharmaDist Inc."),
        ],
    },
    {
        "name": "Doxycycline 100mg Capsules",
        "generic_name": "Doxycycline",
        "brand_name": "Vibramycin",
        "drug_code": "0069-0940-50",
        "form": "capsule",
        "strength": "100mg",
        "unit": "capsule",
        "category": "Antibiotics",
        "manufacturer": "Pfizer",
        "unit_cost": 0.30,
        "selling_price": 0.90,
        "requires_prescription": True,
        "reorder_level": 30,
        "reorder_quantity": 200,
        "batches": [
            ("DOX-2024-001", 250, 0.30, 420, "MedSupply Co."),
        ],
    },
    # ── Analgesics / NSAIDs ──────────────────────────────────────────────────
    {
        "name": "Paracetamol 500mg Tablets",
        "generic_name": "Paracetamol (Acetaminophen)",
        "brand_name": "Panadol",
        "drug_code": "0573-0150-16",
        "form": "tablet",
        "strength": "500mg",
        "unit": "tablet",
        "category": "Analgesics",
        "manufacturer": "GlaxoSmithKline",
        "unit_cost": 0.05,
        "selling_price": 0.20,
        "requires_prescription": False,
        "reorder_level": 100,
        "reorder_quantity": 1000,
        "batches": [
            ("PAR-2024-001", 1000, 0.05, 730, "MedSupply Co."),
            ("PAR-2024-002", 500, 0.05, 540, "MedSupply Co."),
        ],
    },
    {
        "name": "Ibuprofen 400mg Tablets",
        "generic_name": "Ibuprofen",
        "brand_name": "Brufen",
        "drug_code": "0363-0522-10",
        "form": "tablet",
        "strength": "400mg",
        "unit": "tablet",
        "category": "Analgesics",
        "manufacturer": "Abbott",
        "unit_cost": 0.10,
        "selling_price": 0.35,
        "requires_prescription": False,
        "reorder_level": 80,
        "reorder_quantity": 600,
        "batches": [
            ("IBU-2024-001", 600, 0.10, 720, "PharmaDist Inc."),
        ],
    },
    {
        "name": "Diclofenac 50mg Tablets",
        "generic_name": "Diclofenac Sodium",
        "brand_name": "Voltaren",
        "drug_code": "0028-0264-01",
        "form": "tablet",
        "strength": "50mg",
        "unit": "tablet",
        "category": "Analgesics",
        "manufacturer": "Novartis",
        "unit_cost": 0.12,
        "selling_price": 0.40,
        "requires_prescription": True,
        "reorder_level": 50,
        "reorder_quantity": 400,
        "batches": [
            ("DIC-2024-001", 400, 0.12, 480, "MedSupply Co."),
        ],
    },
    {
        "name": "Tramadol 50mg Capsules",
        "generic_name": "Tramadol Hydrochloride",
        "brand_name": "Ultram",
        "drug_code": "0093-0058-01",
        "form": "capsule",
        "strength": "50mg",
        "unit": "capsule",
        "category": "Analgesics",
        "manufacturer": "Teva",
        "unit_cost": 0.40,
        "selling_price": 1.20,
        "requires_prescription": True,
        "is_controlled": True,
        "schedule_class": "IV",
        "reorder_level": 20,
        "reorder_quantity": 100,
        "batches": [
            ("TRA-2024-001", 150, 0.40, 400, "ControlledMed Inc."),
        ],
    },
    # ── Antihypertensives ────────────────────────────────────────────────────
    {
        "name": "Amlodipine 5mg Tablets",
        "generic_name": "Amlodipine Besylate",
        "brand_name": "Norvasc",
        "drug_code": "0069-1520-68",
        "form": "tablet",
        "strength": "5mg",
        "unit": "tablet",
        "category": "Cardiovascular",
        "manufacturer": "Pfizer",
        "unit_cost": 0.18,
        "selling_price": 0.60,
        "requires_prescription": True,
        "reorder_level": 60,
        "reorder_quantity": 500,
        "batches": [
            ("AML-2024-001", 500, 0.18, 540, "CardioPharm Ltd."),
            ("AML-2024-002", 300, 0.18, 700, "CardioPharm Ltd."),
        ],
    },
    {
        "name": "Lisinopril 10mg Tablets",
        "generic_name": "Lisinopril",
        "brand_name": "Zestril",
        "drug_code": "0310-0131-90",
        "form": "tablet",
        "strength": "10mg",
        "unit": "tablet",
        "category": "Cardiovascular",
        "manufacturer": "AstraZeneca",
        "unit_cost": 0.15,
        "selling_price": 0.50,
        "requires_prescription": True,
        "reorder_level": 50,
        "reorder_quantity": 400,
        "batches": [
            ("LIS-2024-001", 400, 0.15, 600, "CardioPharm Ltd."),
        ],
    },
    {
        "name": "Losartan 50mg Tablets",
        "generic_name": "Losartan Potassium",
        "brand_name": "Cozaar",
        "drug_code": "0006-0952-58",
        "form": "tablet",
        "strength": "50mg",
        "unit": "tablet",
        "category": "Cardiovascular",
        "manufacturer": "Merck",
        "unit_cost": 0.20,
        "selling_price": 0.65,
        "requires_prescription": True,
        "reorder_level": 50,
        "reorder_quantity": 400,
        "batches": [
            ("LOS-2024-001", 350, 0.20, 550, "CardioPharm Ltd."),
        ],
    },
    {
        "name": "Atenolol 50mg Tablets",
        "generic_name": "Atenolol",
        "brand_name": "Tenormin",
        "drug_code": "0310-0105-90",
        "form": "tablet",
        "strength": "50mg",
        "unit": "tablet",
        "category": "Cardiovascular",
        "manufacturer": "AstraZeneca",
        "unit_cost": 0.10,
        "selling_price": 0.35,
        "requires_prescription": True,
        "reorder_level": 40,
        "reorder_quantity": 300,
        "batches": [
            ("ATE-2024-001", 300, 0.10, 600, "CardioPharm Ltd."),
        ],
    },
    {
        "name": "Hydrochlorothiazide 25mg Tablets",
        "generic_name": "Hydrochlorothiazide",
        "brand_name": "HydroDIURIL",
        "drug_code": "0006-0042-68",
        "form": "tablet",
        "strength": "25mg",
        "unit": "tablet",
        "category": "Cardiovascular",
        "manufacturer": "Merck",
        "unit_cost": 0.08,
        "selling_price": 0.30,
        "requires_prescription": True,
        "reorder_level": 40,
        "reorder_quantity": 300,
        "batches": [
            ("HCT-2024-001", 300, 0.08, 650, "CardioPharm Ltd."),
        ],
    },
    # ── Antidiabetics ────────────────────────────────────────────────────────
    {
        "name": "Metformin 500mg Tablets",
        "generic_name": "Metformin Hydrochloride",
        "brand_name": "Glucophage",
        "drug_code": "0087-6060-05",
        "form": "tablet",
        "strength": "500mg",
        "unit": "tablet",
        "category": "Antidiabetics",
        "manufacturer": "Bristol-Myers Squibb",
        "unit_cost": 0.08,
        "selling_price": 0.30,
        "requires_prescription": True,
        "reorder_level": 80,
        "reorder_quantity": 600,
        "batches": [
            ("MET-D-2024-001", 600, 0.08, 720, "DiabetesPharm Co."),
            ("MET-D-2024-002", 400, 0.08, 540, "DiabetesPharm Co."),
        ],
    },
    {
        "name": "Glibenclamide 5mg Tablets",
        "generic_name": "Glibenclamide (Glyburide)",
        "brand_name": "Daonil",
        "drug_code": "0039-0051-10",
        "form": "tablet",
        "strength": "5mg",
        "unit": "tablet",
        "category": "Antidiabetics",
        "manufacturer": "Sanofi",
        "unit_cost": 0.12,
        "selling_price": 0.40,
        "requires_prescription": True,
        "reorder_level": 40,
        "reorder_quantity": 300,
        "batches": [
            ("GLI-2024-001", 300, 0.12, 500, "DiabetesPharm Co."),
        ],
    },
    {
        "name": "Insulin Glargine 100 IU/ml Injection",
        "generic_name": "Insulin Glargine",
        "brand_name": "Lantus",
        "drug_code": "0088-2220-52",
        "form": "injection",
        "strength": "100 IU/ml",
        "unit": "vial",
        "category": "Antidiabetics",
        "manufacturer": "Sanofi",
        "unit_cost": 25.00,
        "selling_price": 55.00,
        "requires_prescription": True,
        "storage_conditions": "Refrigerate 2-8°C; discard 28 days after opening",
        "reorder_level": 10,
        "reorder_quantity": 50,
        "batches": [
            ("INS-G-2024-001", 50, 25.00, 300, "InsulinDirect Inc."),
        ],
    },
    # ── Cardiovascular / Lipid-lowering ─────────────────────────────────────
    {
        "name": "Atorvastatin 20mg Tablets",
        "generic_name": "Atorvastatin Calcium",
        "brand_name": "Lipitor",
        "drug_code": "0071-0156-23",
        "form": "tablet",
        "strength": "20mg",
        "unit": "tablet",
        "category": "Cardiovascular",
        "manufacturer": "Pfizer",
        "unit_cost": 0.35,
        "selling_price": 1.00,
        "requires_prescription": True,
        "reorder_level": 50,
        "reorder_quantity": 400,
        "batches": [
            ("ATO-2024-001", 400, 0.35, 600, "CardioPharm Ltd."),
        ],
    },
    {
        "name": "Aspirin 75mg Tablets",
        "generic_name": "Acetylsalicylic Acid",
        "brand_name": "Disprin",
        "drug_code": "0280-0110-01",
        "form": "tablet",
        "strength": "75mg",
        "unit": "tablet",
        "category": "Cardiovascular",
        "manufacturer": "Reckitt Benckiser",
        "unit_cost": 0.04,
        "selling_price": 0.15,
        "requires_prescription": False,
        "reorder_level": 100,
        "reorder_quantity": 1000,
        "batches": [
            ("ASP-2024-001", 1000, 0.04, 730, "PharmaDist Inc."),
        ],
    },
    # ── GI / Antacids ────────────────────────────────────────────────────────
    {
        "name": "Omeprazole 20mg Capsules",
        "generic_name": "Omeprazole",
        "brand_name": "Losec",
        "drug_code": "0186-0742-31",
        "form": "capsule",
        "strength": "20mg",
        "unit": "capsule",
        "category": "Gastrointestinal",
        "manufacturer": "AstraZeneca",
        "unit_cost": 0.20,
        "selling_price": 0.65,
        "requires_prescription": False,
        "reorder_level": 60,
        "reorder_quantity": 500,
        "batches": [
            ("OMP-2024-001", 500, 0.20, 600, "GIPharm Co."),
            ("OMP-2024-002", 300, 0.20, 480, "GIPharm Co."),
        ],
    },
    {
        "name": "Ranitidine 150mg Tablets",
        "generic_name": "Ranitidine Hydrochloride",
        "brand_name": "Zantac",
        "drug_code": "0173-0344-02",
        "form": "tablet",
        "strength": "150mg",
        "unit": "tablet",
        "category": "Gastrointestinal",
        "manufacturer": "GlaxoSmithKline",
        "unit_cost": 0.10,
        "selling_price": 0.35,
        "requires_prescription": False,
        "reorder_level": 50,
        "reorder_quantity": 400,
        "batches": [
            ("RAN-2024-001", 400, 0.10, 550, "GIPharm Co."),
        ],
    },
    {
        "name": "Domperidone 10mg Tablets",
        "generic_name": "Domperidone",
        "brand_name": "Motilium",
        "drug_code": "0362-0210-10",
        "form": "tablet",
        "strength": "10mg",
        "unit": "tablet",
        "category": "Gastrointestinal",
        "manufacturer": "Janssen",
        "unit_cost": 0.10,
        "selling_price": 0.35,
        "requires_prescription": False,
        "reorder_level": 40,
        "reorder_quantity": 300,
        "batches": [
            ("DOM-2024-001", 300, 0.10, 500, "GIPharm Co."),
        ],
    },
    {
        "name": "Loperamide 2mg Capsules",
        "generic_name": "Loperamide Hydrochloride",
        "brand_name": "Imodium",
        "drug_code": "0045-0376-60",
        "form": "capsule",
        "strength": "2mg",
        "unit": "capsule",
        "category": "Gastrointestinal",
        "manufacturer": "Johnson & Johnson",
        "unit_cost": 0.15,
        "selling_price": 0.50,
        "requires_prescription": False,
        "reorder_level": 30,
        "reorder_quantity": 200,
        "batches": [
            ("LOP-2024-001", 200, 0.15, 600, "GIPharm Co."),
        ],
    },
    # ── Respiratory ──────────────────────────────────────────────────────────
    {
        "name": "Salbutamol 100mcg Inhaler",
        "generic_name": "Salbutamol (Albuterol)",
        "brand_name": "Ventolin",
        "drug_code": "0173-0682-20",
        "form": "inhaler",
        "strength": "100mcg/dose",
        "unit": "inhaler",
        "category": "Respiratory",
        "manufacturer": "GlaxoSmithKline",
        "unit_cost": 3.50,
        "selling_price": 9.00,
        "requires_prescription": True,
        "reorder_level": 15,
        "reorder_quantity": 60,
        "batches": [
            ("SAL-2024-001", 60, 3.50, 540, "RespiraMed Ltd."),
        ],
    },
    {
        "name": "Budesonide 200mcg Inhaler",
        "generic_name": "Budesonide",
        "brand_name": "Pulmicort",
        "drug_code": "0186-0905-13",
        "form": "inhaler",
        "strength": "200mcg/dose",
        "unit": "inhaler",
        "category": "Respiratory",
        "manufacturer": "AstraZeneca",
        "unit_cost": 8.00,
        "selling_price": 20.00,
        "requires_prescription": True,
        "reorder_level": 10,
        "reorder_quantity": 40,
        "batches": [
            ("BUD-2024-001", 40, 8.00, 480, "RespiraMed Ltd."),
        ],
    },
    {
        "name": "Cetirizine 10mg Tablets",
        "generic_name": "Cetirizine Hydrochloride",
        "brand_name": "Zyrtec",
        "drug_code": "0069-2550-90",
        "form": "tablet",
        "strength": "10mg",
        "unit": "tablet",
        "category": "Respiratory",
        "manufacturer": "Pfizer",
        "unit_cost": 0.12,
        "selling_price": 0.40,
        "requires_prescription": False,
        "reorder_level": 50,
        "reorder_quantity": 400,
        "batches": [
            ("CET-2024-001", 400, 0.12, 700, "RespiraMed Ltd."),
        ],
    },
    # ── Vitamins & Supplements ───────────────────────────────────────────────
    {
        "name": "Vitamin D3 1000 IU Tablets",
        "generic_name": "Cholecalciferol",
        "brand_name": "D-Vit",
        "drug_code": "0363-0390-90",
        "form": "tablet",
        "strength": "1000 IU",
        "unit": "tablet",
        "category": "Vitamins & Supplements",
        "manufacturer": "Nature's Bounty",
        "unit_cost": 0.05,
        "selling_price": 0.20,
        "requires_prescription": False,
        "reorder_level": 100,
        "reorder_quantity": 1000,
        "batches": [
            ("VITD-2024-001", 1000, 0.05, 730, "VitaSupply Inc."),
        ],
    },
    {
        "name": "Vitamin B Complex Tablets",
        "generic_name": "Thiamine + Riboflavin + Niacin + B6 + B12 + Folic Acid",
        "brand_name": "Becosules",
        "drug_code": "0363-0420-01",
        "form": "tablet",
        "strength": "Standard",
        "unit": "tablet",
        "category": "Vitamins & Supplements",
        "manufacturer": "Pfizer",
        "unit_cost": 0.04,
        "selling_price": 0.15,
        "requires_prescription": False,
        "reorder_level": 100,
        "reorder_quantity": 1000,
        "batches": [
            ("VITB-2024-001", 1000, 0.04, 720, "VitaSupply Inc."),
        ],
    },
    {
        "name": "Iron + Folic Acid Tablets",
        "generic_name": "Ferrous Sulfate 200mg + Folic Acid 0.4mg",
        "brand_name": "Fersolate",
        "drug_code": "0142-0181-30",
        "form": "tablet",
        "strength": "200mg/0.4mg",
        "unit": "tablet",
        "category": "Vitamins & Supplements",
        "manufacturer": "Alliance Pharma",
        "unit_cost": 0.06,
        "selling_price": 0.20,
        "requires_prescription": False,
        "reorder_level": 60,
        "reorder_quantity": 500,
        "batches": [
            ("FER-2024-001", 500, 0.06, 600, "VitaSupply Inc."),
        ],
    },
    {
        "name": "Calcium + Vitamin D3 Tablets",
        "generic_name": "Calcium Carbonate 500mg + Vitamin D3 400IU",
        "brand_name": "Caltrate",
        "drug_code": "0573-0170-60",
        "form": "tablet",
        "strength": "500mg/400 IU",
        "unit": "tablet",
        "category": "Vitamins & Supplements",
        "manufacturer": "Pfizer",
        "unit_cost": 0.08,
        "selling_price": 0.25,
        "requires_prescription": False,
        "reorder_level": 60,
        "reorder_quantity": 500,
        "batches": [
            ("CAL-2024-001", 500, 0.08, 730, "VitaSupply Inc."),
        ],
    },
    # ── Steroids / Anti-inflammatory ─────────────────────────────────────────
    {
        "name": "Prednisolone 5mg Tablets",
        "generic_name": "Prednisolone",
        "brand_name": "Prelone",
        "drug_code": "0254-3505-01",
        "form": "tablet",
        "strength": "5mg",
        "unit": "tablet",
        "category": "Corticosteroids",
        "manufacturer": "Sanofi",
        "unit_cost": 0.08,
        "selling_price": 0.25,
        "requires_prescription": True,
        "reorder_level": 40,
        "reorder_quantity": 300,
        "batches": [
            ("PRED-2024-001", 300, 0.08, 600, "MedSupply Co."),
        ],
    },
    {
        "name": "Dexamethasone 0.5mg Tablets",
        "generic_name": "Dexamethasone",
        "brand_name": "Decadron",
        "drug_code": "0054-4182-25",
        "form": "tablet",
        "strength": "0.5mg",
        "unit": "tablet",
        "category": "Corticosteroids",
        "manufacturer": "Roxane",
        "unit_cost": 0.10,
        "selling_price": 0.35,
        "requires_prescription": True,
        "reorder_level": 30,
        "reorder_quantity": 200,
        "batches": [
            ("DEX-2024-001", 200, 0.10, 550, "MedSupply Co."),
        ],
    },
    # ── Antifungals / Antiparasitics ─────────────────────────────────────────
    {
        "name": "Fluconazole 150mg Capsules",
        "generic_name": "Fluconazole",
        "brand_name": "Diflucan",
        "drug_code": "0069-4210-30",
        "form": "capsule",
        "strength": "150mg",
        "unit": "capsule",
        "category": "Antifungals",
        "manufacturer": "Pfizer",
        "unit_cost": 0.80,
        "selling_price": 2.50,
        "requires_prescription": True,
        "reorder_level": 20,
        "reorder_quantity": 100,
        "batches": [
            ("FLU-2024-001", 100, 0.80, 500, "MedSupply Co."),
        ],
    },
    {
        "name": "Albendazole 400mg Tablets",
        "generic_name": "Albendazole",
        "brand_name": "Zentel",
        "drug_code": "0173-0443-56",
        "form": "tablet",
        "strength": "400mg",
        "unit": "tablet",
        "category": "Antiparasitics",
        "manufacturer": "GlaxoSmithKline",
        "unit_cost": 0.30,
        "selling_price": 1.00,
        "requires_prescription": False,
        "reorder_level": 30,
        "reorder_quantity": 200,
        "batches": [
            ("ALB-2024-001", 200, 0.30, 600, "PharmaDist Inc."),
        ],
    },
    # ── Thyroid ──────────────────────────────────────────────────────────────
    {
        "name": "Levothyroxine 50mcg Tablets",
        "generic_name": "Levothyroxine Sodium",
        "brand_name": "Synthroid",
        "drug_code": "0048-1040-03",
        "form": "tablet",
        "strength": "50mcg",
        "unit": "tablet",
        "category": "Thyroid",
        "manufacturer": "AbbVie",
        "unit_cost": 0.15,
        "selling_price": 0.50,
        "requires_prescription": True,
        "reorder_level": 40,
        "reorder_quantity": 300,
        "batches": [
            ("LEV-2024-001", 300, 0.15, 600, "MedSupply Co."),
        ],
    },
    # ── Antidepressants / Psychiatry ─────────────────────────────────────────
    {
        "name": "Sertraline 50mg Tablets",
        "generic_name": "Sertraline Hydrochloride",
        "brand_name": "Zoloft",
        "drug_code": "0049-4900-66",
        "form": "tablet",
        "strength": "50mg",
        "unit": "tablet",
        "category": "Psychiatry",
        "manufacturer": "Pfizer",
        "unit_cost": 0.25,
        "selling_price": 0.80,
        "requires_prescription": True,
        "reorder_level": 30,
        "reorder_quantity": 200,
        "batches": [
            ("SER-2024-001", 200, 0.25, 600, "MedSupply Co."),
        ],
    },
    {
        "name": "Alprazolam 0.25mg Tablets",
        "generic_name": "Alprazolam",
        "brand_name": "Xanax",
        "drug_code": "0009-0029-01",
        "form": "tablet",
        "strength": "0.25mg",
        "unit": "tablet",
        "category": "Psychiatry",
        "manufacturer": "Pfizer",
        "unit_cost": 0.30,
        "selling_price": 0.90,
        "requires_prescription": True,
        "is_controlled": True,
        "schedule_class": "IV",
        "reorder_level": 15,
        "reorder_quantity": 100,
        "batches": [
            ("ALP-2024-001", 100, 0.30, 500, "ControlledMed Inc."),
        ],
    },
    # ── Topical / Ophthalmic ─────────────────────────────────────────────────
    {
        "name": "Betamethasone 0.1% Cream",
        "generic_name": "Betamethasone Valerate",
        "brand_name": "Betnovate",
        "drug_code": "0173-0403-20",
        "form": "cream",
        "strength": "0.1%",
        "unit": "tube",
        "category": "Topical",
        "manufacturer": "GlaxoSmithKline",
        "unit_cost": 1.50,
        "selling_price": 4.50,
        "requires_prescription": True,
        "reorder_level": 20,
        "reorder_quantity": 100,
        "batches": [
            ("BET-C-2024-001", 100, 1.50, 540, "DermaPharm Inc."),
        ],
    },
    {
        "name": "Ciprofloxacin 0.3% Eye Drops",
        "generic_name": "Ciprofloxacin",
        "brand_name": "Ciloxan",
        "drug_code": "0065-0651-05",
        "form": "eye drops",
        "strength": "0.3% (3mg/ml)",
        "unit": "bottle",
        "category": "Ophthalmic",
        "manufacturer": "Alcon",
        "unit_cost": 3.00,
        "selling_price": 8.50,
        "requires_prescription": True,
        "reorder_level": 15,
        "reorder_quantity": 60,
        "batches": [
            ("CIP-E-2024-001", 60, 3.00, 480, "OphthalmicSupply Ltd."),
        ],
    },
    # ── IV Fluids ────────────────────────────────────────────────────────────
    {
        "name": "Normal Saline 0.9% 500ml",
        "generic_name": "Sodium Chloride",
        "brand_name": "Baxter NS",
        "drug_code": "0338-0004-03",
        "form": "infusion",
        "strength": "0.9% w/v",
        "unit": "bag",
        "category": "IV Fluids",
        "manufacturer": "Baxter",
        "unit_cost": 1.20,
        "selling_price": 3.50,
        "requires_prescription": True,
        "reorder_level": 30,
        "reorder_quantity": 200,
        "batches": [
            ("NS-2024-001", 200, 1.20, 540, "HospitalSupply Co."),
        ],
    },
    {
        "name": "Dextrose 5% 500ml",
        "generic_name": "Glucose",
        "brand_name": "Baxter D5W",
        "drug_code": "0338-0017-03",
        "form": "infusion",
        "strength": "5% w/v",
        "unit": "bag",
        "category": "IV Fluids",
        "manufacturer": "Baxter",
        "unit_cost": 1.30,
        "selling_price": 3.80,
        "requires_prescription": True,
        "reorder_level": 30,
        "reorder_quantity": 200,
        "batches": [
            ("D5W-2024-001", 200, 1.30, 540, "HospitalSupply Co."),
        ],
    },
    {
        "name": "Ringer's Lactate 500ml",
        "generic_name": "Sodium Lactate Compound",
        "brand_name": "Hartmann's Solution",
        "drug_code": "0338-0115-03",
        "form": "infusion",
        "strength": "Compound",
        "unit": "bag",
        "category": "IV Fluids",
        "manufacturer": "Baxter",
        "unit_cost": 1.40,
        "selling_price": 4.00,
        "requires_prescription": True,
        "reorder_level": 30,
        "reorder_quantity": 200,
        "batches": [
            ("RL-2024-001", 200, 1.40, 540, "HospitalSupply Co."),
        ],
    },
    # ── Vaccines (refrigerated) ──────────────────────────────────────────────
    {
        "name": "Hepatitis B Vaccine 1ml",
        "generic_name": "Hepatitis B Surface Antigen",
        "brand_name": "Engerix-B",
        "drug_code": "0173-0392-01",
        "form": "injection",
        "strength": "20mcg/ml",
        "unit": "vial",
        "category": "Vaccines",
        "manufacturer": "GlaxoSmithKline",
        "unit_cost": 8.00,
        "selling_price": 20.00,
        "requires_prescription": True,
        "storage_conditions": "Refrigerate 2-8°C; do not freeze",
        "reorder_level": 10,
        "reorder_quantity": 30,
        "batches": [
            ("HBV-2024-001", 30, 8.00, 365, "VaccineSupply Inc."),
        ],
    },
    {
        "name": "Tetanus Toxoid 0.5ml",
        "generic_name": "Tetanus Toxoid",
        "brand_name": "Tetavax",
        "drug_code": "49281-0820-10",
        "form": "injection",
        "strength": "40 IU/0.5ml",
        "unit": "vial",
        "category": "Vaccines",
        "manufacturer": "Sanofi Pasteur",
        "unit_cost": 2.50,
        "selling_price": 7.00,
        "requires_prescription": True,
        "storage_conditions": "Refrigerate 2-8°C; do not freeze",
        "reorder_level": 10,
        "reorder_quantity": 30,
        "batches": [
            ("TT-2024-001", 30, 2.50, 365, "VaccineSupply Inc."),
        ],
    },
]


# ── Seed function ─────────────────────────────────────────────────────────────

async def seed_medicines(session: AsyncSession) -> None:
    today = date.today()
    seeded = skipped = 0

    for drug_data in DRUGS:
        # Check if drug already exists (by name + clinic)
        existing = await session.scalar(
            select(DrugItem).where(
                DrugItem.clinic_id == DEMO_CLINIC_ID,
                DrugItem.name == drug_data["name"],
                DrugItem.is_deleted.isnot(True),
            )
        )
        if existing:
            skipped += 1
            continue

        drug_id = str(uuid.uuid4())
        drug = DrugItem(
            id=drug_id,
            tenant_id=DEMO_TENANT_ID,
            clinic_id=DEMO_CLINIC_ID,
            name=drug_data["name"],
            generic_name=drug_data.get("generic_name"),
            brand_name=drug_data.get("brand_name"),
            drug_code=drug_data.get("drug_code"),
            form=drug_data["form"],
            strength=drug_data["strength"],
            unit=drug_data["unit"],
            category=drug_data.get("category"),
            manufacturer=drug_data.get("manufacturer"),
            unit_cost=drug_data["unit_cost"],
            selling_price=drug_data["selling_price"],
            requires_prescription=drug_data.get("requires_prescription", True),
            is_controlled=drug_data.get("is_controlled", False),
            schedule_class=drug_data.get("schedule_class"),
            storage_conditions=drug_data.get("storage_conditions"),
            reorder_level=drug_data.get("reorder_level", 10),
            reorder_quantity=drug_data.get("reorder_quantity", 100),
            is_active=True,
        )
        session.add(drug)
        await session.flush()  # get drug.id

        # Create stock batches
        for batch_no, qty, unit_cost, expiry_days, supplier in drug_data.get("batches", []):
            expiry_date = (today + timedelta(days=expiry_days)).isoformat()
            session.add(StockBatch(
                id=str(uuid.uuid4()),
                tenant_id=DEMO_TENANT_ID,
                drug_item_id=drug_id,
                batch_number=batch_no,
                quantity=qty,
                quantity_remaining=qty,
                unit_cost=unit_cost,
                expiry_date=expiry_date,
                received_date=TODAY,
                supplier_name=supplier,
                is_active=True,
            ))

        print(f"  [+] {drug_data['name']}")
        seeded += 1

    print(f"\n  Done — {seeded} drugs seeded, {skipped} already existed.")


async def main() -> None:
    engine = create_async_engine(settings.DATABASE_URL, echo=False)
    async_session = async_sessionmaker(engine, expire_on_commit=False)

    print("\n=== Seeding Pharmacy Medicines ===")
    async with async_session() as session:
        async with session.begin():
            await seed_medicines(session)

    await engine.dispose()
    print("=== Done ===\n")


if __name__ == "__main__":
    asyncio.run(main())
