"""add_specializations_table

Revision ID: 3dd279cbf9ce
Revises: 
Create Date: 2026-03-27 15:19:39.487119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd279cbf9ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'appointment_waitlists', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'audit_logs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chronic_conditions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clinic_rooms', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'clinics', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'doctor_clinic_assignments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'doctor_ratings', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'doctor_schedule_exceptions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'doctor_schedules', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'doctors', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'drug_items', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'emergency_contacts', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'insurance_claims', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'insurance_policies', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invoice_items', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invoices', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lab_order_items', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lab_orders', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lab_reports', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'medical_record_addenda', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'medical_records', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patient_allergies', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patient_family_links', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patients', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'prescription_items', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'prescription_refill_requests', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'prescriptions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'purchase_order_items', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'purchase_orders', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stock_batches', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stock_transactions', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'stock_transactions', type_='foreignkey')
    op.drop_constraint(None, 'stock_batches', type_='foreignkey')
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_constraint(None, 'purchase_order_items', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', type_='foreignkey')
    op.drop_constraint(None, 'prescription_refill_requests', type_='foreignkey')
    op.drop_constraint(None, 'prescription_items', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patient_family_links', type_='foreignkey')
    op.drop_constraint(None, 'patient_allergies', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_constraint(None, 'medical_record_addenda', type_='foreignkey')
    op.drop_constraint(None, 'lab_reports', type_='foreignkey')
    op.drop_constraint(None, 'lab_orders', type_='foreignkey')
    op.drop_constraint(None, 'lab_order_items', type_='foreignkey')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.drop_constraint(None, 'insurance_policies', type_='foreignkey')
    op.drop_constraint(None, 'insurance_claims', type_='foreignkey')
    op.drop_constraint(None, 'emergency_contacts', type_='foreignkey')
    op.drop_constraint(None, 'drug_items', type_='foreignkey')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_constraint(None, 'doctor_schedules', type_='foreignkey')
    op.drop_constraint(None, 'doctor_schedule_exceptions', type_='foreignkey')
    op.drop_constraint(None, 'doctor_ratings', type_='foreignkey')
    op.drop_constraint(None, 'doctor_clinic_assignments', type_='foreignkey')
    op.drop_constraint(None, 'clinics', type_='foreignkey')
    op.drop_constraint(None, 'clinic_rooms', type_='foreignkey')
    op.drop_constraint(None, 'chronic_conditions', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointment_waitlists', type_='foreignkey')
    # ### end Alembic commands ###
